/**
 * Extended certification data with IDs and credential URLs.
 * @const
 */
const CERTIFICATIONS = [
  {
    id: 17,
    title: 'IriusRisk - Threat Modeling Champion (IR-TMC)',
    emit: 'IriusRisk',
    emitURL: '',
    credID: '703a2073-9953-4c84-b141-895ce34b16b9',
    URL: '',
  },
  {
    id: 16,
    title: 'CVSS v4.0 Certificate',
    emit: 'FIRST',
    emitURL: '',
    credID: '',
    URL: '',
  },
  {
    id: 15,
    title: 'Web Application Penetration Tester (eWPT)',
    emit: 'INE',
    emitURL: '',
    credID: '',
    URL: '',
  },
  {
    id: 14,
    title: 'Junior Penetration Tester (eJPT)',
    emit: 'INE',
    emitURL: '',
    credID: '',
    URL: '',
  },
  {
    id: 13,
    title: 'Certified AppSec Practitioner (CAP)',
    emit: 'The SecOps Group',
    emitURL: '',
    credID: '7030773',
    URL: '',
  },
  {
    id: 12,
    title: 'Security Guardian',
    emit: 'Mercado Libre',
    emitURL: 'https://www.linkedin.com/company/mercadolibre/',
    credID: '',
    URL: '',
  },
  {
    id: 11,
    title: 'Certified Backend Secure Developer',
    emit: 'Secure Code Warrior',
    emitURL: '',
    credID: '',
    URL: '',
  },
  {
    id: 10,
    title: 'OWASP Top 10 — Node.js',
    emit: 'Callstrike',
    emitURL: '',
    credID: '',
    URL: '',
  },
  {
    id: 9,
    title: 'PCEP — Certified Entry-Level Python Programmer',
    emit: 'OpenEDG Python Institute',
    emitURL: '',
    credID: '0y4i.be5p.c7KL',
    URL: '',
  },
  {
    id: 8,
    title: 'AWS Technical Essentials',
    emit: 'Amazon Web Services (AWS)',
    emitURL: '',
    credID: '',
    URL: '',
  },
  {
    id: 7,
    title: 'GOLANG — Curso profesional de Go',
    emit: 'Udemy',
    emitURL: '',
    credID: 'UC-56d7c9db-8b2a-44d0-b2b9-a916978ca1df',
    URL: '',
  },
  {
    id: 6,
    title: 'JavaScript Algorithms and Data Structures',
    emit: 'freeCodeCamp',
    emitURL: 'https://www.linkedin.com/school/free-code-camp/',
    credID: '',
    URL: 'https://www.freecodecamp.org/certification/peterdg/javascript-algorithms-and-data-structures',
  },
  {
    id: 5,
    title: 'Aceleración FullStack en React, Node. Job Ready.',
    emit: 'Alkemy',
    emitURL: 'https://www.linkedin.com/company/alkemy2020/',
    credID: '042-344',
    URL: 'https://drive.google.com/file/d/1Ok8El_CKfCYyhfnkDs6v7FC7oIElLb9W/view',
  },
  {
    id: 4,
    title: 'Acuerdo y Resolución de Conflictos',
    emit: 'Axialent',
    emitURL: '',
    credID: '6e6c4279-ee45-4211-8ae8-1d89d5cc7625',
    URL: '',
  },
  {
    id: 3,
    title: 'Conversaciones Auténticas y Efectivas',
    emit: 'Axialent',
    emitURL: '',
    credID: 'dece5616-0ae6-42a6-9244-934eb5f0e808',
    URL: '',
  },
  {
    id: 2,
    title: 'Taller del Tiempo',
    emit: 'Kleer',
    emitURL: '',
    credID: 'xtzp9d30',
    URL: '',
  },
  {
    id: 1,
    title: 'Google Activate Cloud Computing',
    emit: 'Google Actívate',
    emitURL: 'https://www.linkedin.com/company/activatecongoogle/',
    credID: 'SJ5 A65 58Z',
    URL: 'https://learndigital.withgoogle.com/activate/validate-certificate-code',
  },
  {
    id: 0,
    title: 'EF SET English Certificate 49/100 (B1 Intermediate)',
    emit: 'EF Standard English Test (EF SET)',
    emitURL: 'https://www.linkedin.com/company/efset/',
    credID: '',
    URL: 'https://www.efset.org/cert/QAFMtr',
  },
] as const;

export default CERTIFICATIONS;
